### ISSUE TITLE
Release attachment

### ISSUE THREAD

**Issue by jameskoster** [seb86/Storefront-Beta-Tester#2]
This just occurred to me as a potential issue. We don't track minified/compressed assets in version control. That means no css either. So if you were to simply download a tag and install it, it wouldn't work. 

We attach a `storefront.zip` file manually to each tag. Is there any way this plugin can look for that?

**Comment by BurlesonBrad** [comment]
mental notes: _(to be figured out when I'm not stalking git for awesome snippets)_
test what happens if I change either lines
https://github.com/seb86/Storefront-Beta-Tester/blob/master/storefront-beta-tester.php#L92
https://github.com/seb86/Storefront-Beta-Tester/blob/master/storefront-beta-tester.php#L68
to this url:
https://github.com/woothemes/storefront/archive/master.zip

**Comment by seb86** [comment]
@jameskoster OK. I see what you mean.

So at the moment, it currently reads this link once a release has been made: https://github.com/woothemes/storefront/archive/version/2.0.0-beta-1.zip

We need to change it to look for this: https://github.com/woothemes/storefront/releases/download/version%2F2.0.0-beta-1/storefront.zip

**Comment by seb86** [comment]
I pushed a quick update. https://github.com/seb86/Storefront-Beta-Tester/commit/3189cebb6e573e52ebff03b0ad7ca7c0be0fa24f

**Comment by jameskoster** [comment]
Sweet!
